#pragma config(Sensor, S2,     sLights,        sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-ev3lights.h";

task main()
{
	EV3Lights(sLights, colorBlue, 0);
	EV3Lights(sLights, colorRed, 0);
	EV3Lights(sLights, colorGreen, 0);
	sleep(5000);
	bool bGreen = true;

	while(true)
	{
		bGreen = ! bGreen;
		if (bGreen)
		{
			EV3Lights(sLights, colorRed, 0);
			EV3Lights(sLights, colorGreen, 254);
			sleep(5000);
			for ( int i = 0 ; i < 3; i ++)
			{
				EV3Lights(sLights, colorGreen, 0);
				sleep(300);
				EV3Lights(sLights, colorGreen, 254);
				sleep(300);
			}
		}
		else
		{
			EV3Lights(sLights, colorRed, 254);
			EV3Lights(sLights, colorGreen, 0);
			sleep(5000);
		}
	}


	sleep(5000);
}
